defaults: &defaults
  site:
    name: "StackTXT"
    title_seprator: "--"

  message:
    expire: 300 # 5 minutes
    max_view_count: 16 
    max_length: 1024

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
