defaults: &defaults
  site:
    name: "stacktxt"
    title_seprator: "--"

  message:
    expire: 300 # 5 minutes
    max_view_count: 16 

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
